version: "3.9"

services:
  backend:
    build: ./infra/docker
    container_name: artesanos-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: artesanos-db
    environment:
      POSTGRES_DB: artesanos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  frontend:
    image: nginx
    container_name: artesanos-frontend
    ports:
      - "3000:80"
    volumes:
      - ./src/frontend:/usr/share/nginx/html
